version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localnotes-localstack
    ports:
      - "4566:4566"  # Edge port for all AWS services
      - "4571:4571"  # Optional (deprecated port)
    environment:
      - SERVICES=lambda,dynamodb,apigateway
      - LAMBDA_EXECUTOR=docker
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_REGION}     
    volumes:
      - ./backend/scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - "./localstack-data:/temp/localstack"  # Persist data
      - "/var/run/docker.sock:/var/run/docker.sock"  # Required for Lambda
